//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicio_rutina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejercicio_rutina()
        {
            this.Rutina1 = new HashSet<Rutina>();
        }
    
        public int Id_ejercicio_rutina { get; set; }
        public int id_Rutina { get; set; }
        public string repeticiones { get; set; }
        public int series { get; set; }
        public int id_ejercicio { get; set; }
    
        public virtual Ejercicio Ejercicio { get; set; }
        public virtual Rutina Rutina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rutina> Rutina1 { get; set; }
    }
}
