//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perfil()
        {
            this.Rutina = new HashSet<Rutina>();
        }

        public Perfil(string id)
        {
            this.ID_PERFIL = id;
        }
    
        public string ID_PERFIL { get; set; }
        public string perfilNombre { get; set; }
        public string perfilApellido { get; set; }
        public Nullable<System.DateTime> perfilEdad { get; set; }
        public Nullable<int> perfilAltura { get; set; }
        public Nullable<int> perfilPeso { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rutina> Rutina { get; set; }
    }
}
