//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peso_Usuario
    {
        public int ID_PESO { get; set; }
        public int ID_PERFIL { get; set; }
        public int peso { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
