//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rutina()
        {
            this.Ejercicio_rutina = new HashSet<Ejercicio_rutina>();
        }
    
        public int ID_RUTINA { get; set; }
        public string rutNombre { get; set; }
        public System.DateTime rutFechaCreacion { get; set; }
        public int ID_PERFIL { get; set; }
        public int ID_Ejercicio_Rutina { get; set; }
        public int dias_por_semana { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ejercicio_rutina> Ejercicio_rutina { get; set; }
        public virtual Ejercicio_rutina Ejercicio_rutina1 { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
